export const SHOW_TEXT='SHOW_TEXT'
export const ADD_TODOLIST='ADD_TODOLIST'
export const REMOVE_TODOLIST='REMOVE_TODOLIST'
export const CHANGE_TODOLIST='CHANGE_TODOLIST'

//设置显示页面
export const CHANGE_PAGESHOW='CHANGE_PAGESHOW'
// 车型详情logo大图
export const SET_DETAILIMG='SET_DETAILIMG'
// 车辆图片列表
export const SET_CARIMGLIST='SET_CARIMGLIST'
// 设置用户位置信息
export const SET_USERSIZE='SET_USERSIZE'
export const SET_USERINFO='SET_USERINFO'
export const SET_IFRAMEDATA='SET_IFRAMEDATA'
export const SET_HISTORY='SET_HISTORY'
export const SET_WECHATUSERINGO='SET_WECHATUSERINGO'
